"""Execute ordinary Python cells and preserve stream outputs without Jupyter dependencies."""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import traceback
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("output")
    parser.add_argument(
        "--run-mode",
        choices=("smoke", "lfw"),
        help="Override the generated notebook's default RUN_MODE for validation.",
    )
    args = parser.parse_args()
    input_path, output_path = Path(args.input), Path(args.output)
    notebook = json.loads(input_path.read_text(encoding="utf-8"))
    if args.run_mode:
        marker = 'RUN_MODE = "smoke"  # @param ["smoke", "lfw"]'
        replacement = f'RUN_MODE = "{args.run_mode}"  # locally validated override'
        matches = 0
        for cell in notebook["cells"]:
            if cell["cell_type"] == "code" and marker in cell["source"]:
                cell["source"] = cell["source"].replace(marker, replacement)
                matches += 1
        if matches != 1:
            raise RuntimeError(f"expected exactly one RUN_MODE marker, found {matches}")
    namespace: dict[str, object] = {"__name__": "__notebook__"}
    execution_count = 0
    old_cwd = Path.cwd()
    os.chdir(input_path.resolve().parents[1])
    try:
        for cell in notebook["cells"]:
            if cell["cell_type"] != "code":
                continue
            execution_count += 1
            stdout, stderr = io.StringIO(), io.StringIO()
            try:
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    # This development helper executes only the notebook generated by this
                    # repository; it is not a general untrusted-notebook runner.
                    exec(  # noqa: S102
                        compile(cell["source"], f"cell-{execution_count}", "exec"), namespace
                    )
            except Exception:
                traceback.print_exc(file=stderr)
                cell["outputs"] = []
                if stdout.getvalue():
                    cell["outputs"].append(
                        {"name": "stdout", "output_type": "stream", "text": stdout.getvalue()}
                    )
                cell["outputs"].append(
                    {"name": "stderr", "output_type": "stream", "text": stderr.getvalue()}
                )
                cell["execution_count"] = execution_count
                output_path.write_text(json.dumps(notebook, indent=1) + "\n", encoding="utf-8")
                raise
            cell["outputs"] = []
            if stdout.getvalue():
                cell["outputs"].append(
                    {"name": "stdout", "output_type": "stream", "text": stdout.getvalue()}
                )
            if stderr.getvalue():
                cell["outputs"].append(
                    {"name": "stderr", "output_type": "stream", "text": stderr.getvalue()}
                )
            cell["execution_count"] = execution_count
    finally:
        os.chdir(old_cwd)
    output_path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(output_path)


if __name__ == "__main__":
    main()
